# Instalación de dnsmasq
 sudo apt install dnsmasq

# Configuración DNS local personalizada
 address=/hackathon.local/192.168.0.9

# Reiniciar servicio
 sudo systemctl restart dnsmasq

# Prueba de resolución DNS
 dig hackathon.local @127.0.0.1
