name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main


jobs:

  lint:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install Ruff
        run: pip install ruff


      - name: Lint
        run: ruff check .


  test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: pip install -e ".[test]"


      - name: Run Tests
        run: pytest --cov
